-- reprove:force-row-level-security
ALTER TABLE "enrollment_code" FORCE ROW LEVEL SECURITY;
ALTER TABLE "finding" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ingress_delivery" FORCE ROW LEVEL SECURITY;
ALTER TABLE "installation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "owner" FORCE ROW LEVEL SECURITY;
ALTER TABLE "publication" FORCE ROW LEVEL SECURITY;
ALTER TABLE "repository" FORCE ROW LEVEL SECURITY;
ALTER TABLE "run" FORCE ROW LEVEL SECURITY;
ALTER TABLE "worker" FORCE ROW LEVEL SECURITY;
ALTER TABLE "worker_credential" FORCE ROW LEVEL SECURITY;
